pr:
- main

pool:
  name: VSEngSS-MicroBuild2019-1ES

variables:
  TeamName: TypeScript

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.x'
- task: CredScan@3
- task: PoliCheck@2
- task: AntiMalware@4
- task: PublishSecurityAnalysisLogs@3
- task: PostAnalysis@2

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'
- script: |
    npm ci
    npm run build
  displayName: 'npm install and build'

- task: MicroBuildCleanup@1
